// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqO7nPKCY6SejJNHJ3l97hsShy84hT4_k',
    appId: '1:792866171110:web:a692d47d21f2c486a63327',
    messagingSenderId: '792866171110',
    projectId: 'food-app-project-24353',
    authDomain: 'food-app-project-24353.firebaseapp.com',
    storageBucket: 'food-app-project-24353.appspot.com',
    measurementId: 'G-7178X05ZC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPk_OXBN2JZh2Wlhoe_SUlfS-0S8Lf9Xg',
    appId: '1:792866171110:android:e6f604345ea42e3ba63327',
    messagingSenderId: '792866171110',
    projectId: 'food-app-project-24353',
    storageBucket: 'food-app-project-24353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATQ8h235n7gVoCuO2fK_wgMrTckxptphc',
    appId: '1:792866171110:ios:f8f2039c3e4b81c7a63327',
    messagingSenderId: '792866171110',
    projectId: 'food-app-project-24353',
    storageBucket: 'food-app-project-24353.appspot.com',
    iosClientId: '792866171110-vcqk179v7960gftt84edrdntkddd32ru.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
